### ISSUE TITLE
500 error in /admin

### ISSUE THREAD

**Issue by jonekdahl** [valtech/valtech-shortie#33]
This problem has been discussed back and forth on different channels but here's a short summary.

When logging in to Shortie /admin after authenticating in Valtech IDP, you get a 500 error page. The following error occurs in the log:

```
2016-04-28 19:52:24.814 2016-04-28T19:52:25.082Z info 302 GET 12ms /admin {}
2016-04-28 19:52:24.814 2016-04-28T19:52:25.253Z info oauth2 redirecting to authorize {"url":"https://id.valtech.com/oauth2/authorize?response_type=code&client_id=valtech.shortie&scope=profile%20email&state=cecb41e1-72fb-4fd4-b48f-8d697b6d9040"}
2016-04-28 19:52:24.931 2016-04-28T19:52:25.253Z info 302 GET 15ms /login?redirect=%2Fadmin {}
2016-04-28 19:52:25.724 2016-04-28T19:52:26.125Z error unhandled error Error: SELF_SIGNED_CERT_IN_CHAIN
    at SecurePair.<anonymous> (tls.js:1370:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read] (tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24) {}

Go to the log: https://logentries.com/app/4092e6e9#/log/328dc269
```

The problem occurs when Shortie calls IDP to get an access token. What the error probably means is that the new *.valtech.com certificate issuer is not trusted by Shortie. The same error occurs on a local dev machine with node v0.10.25. Upgrading to the latest 0.10.x version (currently 0.10.44) fixes the problem locally.

**Comment by jonekdahl** [comment]
To fix this I tried to upgrade the version we use on Azure by changing `WEBSITE_NODE_DEFAULT_VERSION` for [stage-valtech-shortie](https://manage.windowsazure.com/valtech.com#Workspaces/WebsiteExtension/Website/stage-valtech-shortie/configure) in the Azure portal. I tried both 0.10.44 and 0.10.40 but it didn't make a difference.

According to [this blogpost](http://hardcoded.se/2015/01/07/node-js-version-on-azure-websites/), the available node versions are listed here: 
https://stage-valtech-shortie.scm.azurewebsites.net/api/diagnostics/runtime.

**Comment by jonekdahl** [comment]
Since I could not confirm that the Azure website setting was working, I also tried to change the node version through package.json. However, that change never got deployed to Azure because the [CI build](https://bob.valtech.se/viewType.html?buildTypeId=InternalSystems_ValteCh_1BuildTestLintAndIntegrationTest) failed. The TeamCity build agent reports that it is using node 4.2.6, which might be what causes the build to fail.

**Comment by jonekdahl** [comment]
I cheated by temporarily disabling the integrationTest build step that failed, and the application is now running OK again, both stage and prod.
